GET http://localhost:8989/user

###

POST http://localhost:8989/user
content-type: application/json

{
    "caption": "Nastya",
    "description": "new user Nastya"
}

###

PUT http://localhost:8989/user
content-type: application/json

{
    "id": 5,
    "caption": "Nastya updated",
    "description": "new user Nastya"
}